/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.GestorMedicoControl;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kgramirez
 */
public class ConsConsultorioInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsConsultorioInternalFrame
     */
    public Controlador.GestorConsultorioControl gestorConsultorioControl;
    private DefaultTableModel tablaCon;
    
    public ConsConsultorioInternalFrame() {
        initComponents();
        gestorConsultorioControl = new Controlador.GestorConsultorioControl(this);
        String titulosTabla[] = {"Numero", "Nombre"};
        tablaCon = new DefaultTableModel(null, titulosTabla);
        Tbl_datosMed.setModel(tablaCon);
        btn_aceptar.addActionListener((ActionListener) gestorConsultorioControl);
    }
    public DefaultTableModel getTableModel(){
    return tablaCon;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_valor = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datosMed = new javax.swing.JTable();
        rdb_ConNumero = new javax.swing.JRadioButton();
        rdb_ConNombres = new javax.swing.JRadioButton();

        setTitle("Consultar consultorio");

        txt_valor.setText("Consulta consultorio");

        jTextField1.setName("ValorTxt"); // NOI18N

        btn_aceptar.setText("Consultar");
        btn_aceptar.setName("AceptarBtn"); // NOI18N

        Tbl_datosMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datosMed.setName("ResultadosTbl"); // NOI18N
        jScrollPane1.setViewportView(Tbl_datosMed);

        rdb_ConNumero.setText("Número");
        rdb_ConNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_ConNumeroActionPerformed(evt);
            }
        });

        rdb_ConNombres.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txt_valor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(rdb_ConNumero)
                        .addGap(31, 31, 31)
                        .addComponent(rdb_ConNombres)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_ConNumero)
                    .addComponent(rdb_ConNombres))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_valor)
                        .addComponent(btn_aceptar))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_ConNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_ConNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_ConNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tbl_datosMed;
    public javax.swing.JButton btn_aceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton rdb_ConNombres;
    public javax.swing.JRadioButton rdb_ConNumero;
    public javax.swing.JLabel txt_valor;
    // End of variables declaration//GEN-END:variables
}
