/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kgramirez
 */
public class ConsTratamientoInternalFrame extends javax.swing.JInternalFrame {
    
    public Controlador.GestorTratamientoControl gestortratamientoControl;
    private DefaultTableModel tablaTratam;
    /**
     * Creates new form ConsTratamientoInternalFrame
     */
    public ConsTratamientoInternalFrame() {
        initComponents();
        gestortratamientoControl =new Controlador.GestorTratamientoControl(this);
        String titulosTabla[]={"Numero","Fecha asiganda","Descripcion","Fecha inicio", "Fecha fin", "Observaciones", "Paciente"};     
        tablaTratam=new DefaultTableModel(null, titulosTabla);
        Tbl_datosTratam.setModel(tablaTratam);
        btnTratamBuscar.addActionListener((ActionListener) gestortratamientoControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FechaAsig = new javax.swing.JRadioButton();
        DesTratam = new javax.swing.JRadioButton();
        FechaFinal = new javax.swing.JRadioButton();
        Pacien = new javax.swing.JRadioButton();
        NumTratam = new javax.swing.JRadioButton();
        FechaIni = new javax.swing.JRadioButton();
        txtTraValor = new javax.swing.JTextField();
        btnTratamBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datosTratam = new javax.swing.JTable();
        TraObser = new javax.swing.JRadioButton();

        setTitle("Consultar Tratamiento");

        FechaAsig.setText("Fecha asignada");
        FechaAsig.setOpaque(false);

        DesTratam.setText("Descripcion");
        DesTratam.setOpaque(false);

        FechaFinal.setText("Fecha final");
        FechaFinal.setOpaque(false);

        Pacien.setText("Paciente");
        Pacien.setOpaque(false);

        NumTratam.setText("Numero");
        NumTratam.setOpaque(false);

        FechaIni.setText("Fecha inicio");
        FechaIni.setOpaque(false);

        btnTratamBuscar.setText("Buscar");
        btnTratamBuscar.setOpaque(false);

        jLabel2.setText("Valor a buscar:");

        Tbl_datosTratam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datosTratam.setName("ResultadosTbl"); // NOI18N
        jScrollPane1.setViewportView(Tbl_datosTratam);

        TraObser.setText("Observaciones");
        TraObser.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NumTratam)
                                        .addGap(18, 18, 18)
                                        .addComponent(FechaAsig))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FechaIni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FechaFinal)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TraObser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pacien))
                                    .addComponent(DesTratam)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnTratamBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumTratam)
                    .addComponent(DesTratam)
                    .addComponent(FechaAsig))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaIni)
                    .addComponent(FechaFinal)
                    .addComponent(Pacien)
                    .addComponent(TraObser))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTratamBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton DesTratam;
    public javax.swing.JRadioButton FechaAsig;
    public javax.swing.JRadioButton FechaFinal;
    public javax.swing.JRadioButton FechaIni;
    public javax.swing.JRadioButton NumTratam;
    public javax.swing.JRadioButton Pacien;
    public javax.swing.JTable Tbl_datosTratam;
    public javax.swing.JRadioButton TraObser;
    public javax.swing.JButton btnTratamBuscar;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtTraValor;
    // End of variables declaration//GEN-END:variables
}
