/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kgramirez
 */
public class ConsCitasInternalFrame extends javax.swing.JInternalFrame {

    public Controlador.GestorCitasControl gestorcitasControl;
    private DefaultTableModel tablaCitas;
    /**
     * Creates new form ConsCitasInternalFrame
     */
    public ConsCitasInternalFrame() {
        initComponents();
        gestorcitasControl =new Controlador.GestorCitasControl(this);
        String titulosTabla[]={"Numero","Fecha","Hora","Paciente", "Medico", "Consultorio", "Estado", "Observaciones"};     
        tablaCitas=new DefaultTableModel(null, titulosTabla);
        Tbl_datosCita.setModel(tablaCitas);
        btnBuscar.addActionListener((ActionListener) gestorCitasControl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        Fecha = new javax.swing.JRadioButton();
        Hora = new javax.swing.JRadioButton();
        Consultorio = new javax.swing.JRadioButton();
        Observaciones = new javax.swing.JRadioButton();
        Estado = new javax.swing.JRadioButton();
        Paciente = new javax.swing.JRadioButton();
        Medico = new javax.swing.JRadioButton();
        Numero = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datosCita = new javax.swing.JTable();

        setTitle("Consultar citas");

        jLabel2.setText("Valor a buscar:");

        btnBuscar.setText("Buscar");

        Fecha.setText("Fecha");
        Fecha.setOpaque(false);

        Hora.setText("Hora");
        Hora.setOpaque(false);

        Consultorio.setText("Consultorio");
        Consultorio.setOpaque(false);

        Observaciones.setText("Observaciones");
        Observaciones.setOpaque(false);

        Estado.setText("Estado");
        Estado.setOpaque(false);

        Paciente.setText("Paciente");
        Paciente.setOpaque(false);

        Medico.setText("Medico");
        Medico.setOpaque(false);

        Numero.setText("Numero");
        Numero.setOpaque(false);
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });

        Tbl_datosCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datosCita.setName("ResultadosTbl"); // NOI18N
        jScrollPane1.setViewportView(Tbl_datosCita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consultorio)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Hora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Paciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Medico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Estado)
                                .addGap(18, 18, 18)
                                .addComponent(Observaciones)
                                .addGap(84, 84, 84))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Numero)
                            .addComponent(Fecha)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Medico)
                            .addComponent(Paciente)
                            .addComponent(Hora))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultorio)
                    .addComponent(Estado)
                    .addComponent(Observaciones))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Consultorio;
    public javax.swing.JRadioButton Estado;
    public javax.swing.JRadioButton Fecha;
    public javax.swing.JRadioButton Hora;
    public javax.swing.JRadioButton Medico;
    public javax.swing.JRadioButton Numero;
    public javax.swing.JRadioButton Observaciones;
    public javax.swing.JRadioButton Paciente;
    public javax.swing.JTable Tbl_datosCita;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
