/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author kgramirez
 */
public class RegconsultorioInternalFrame extends javax.swing.JInternalFrame {

    private Controlador.ConsultorioControl consultorioControlador;
    /**
     * Creates new form RegconsultorioInternalFrame
     */
    public RegconsultorioInternalFrame() {
        initComponents();
        consultorioControlador  = new Controlador.ConsultorioControl(this);
        btn_registrarCon.addActionListener(consultorioControlador);
        btn_nuevoCon.addActionListener(consultorioControlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ConNumero = new javax.swing.JTextField();
        txt_ConNombre = new javax.swing.JTextField();
        btn_registrarCon = new javax.swing.JButton();
        btn_nuevoCon = new javax.swing.JButton();

        setTitle("Registro Consultorio");

        jLabel1.setText("Número:");

        jLabel2.setText("Nombre:");

        txt_ConNumero.setName("IdentificaciónTxt"); // NOI18N

        txt_ConNombre.setName("NombresTxt"); // NOI18N
        txt_ConNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ConNombreActionPerformed(evt);
            }
        });

        btn_registrarCon.setText("Registrar");
        btn_registrarCon.setName("RegistrarBtn"); // NOI18N
        btn_registrarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarConActionPerformed(evt);
            }
        });

        btn_nuevoCon.setText("Nuevo");
        btn_nuevoCon.setName("NuevoBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(btn_registrarCon))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_nuevoCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ConNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ConNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 31, Short.MAX_VALUE)))
                    .addGap(84, 84, 84)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_ConNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ConNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)))
                    .addGap(82, 82, 82)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_registrarCon)
                        .addComponent(btn_nuevoCon))
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ConNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ConNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ConNombreActionPerformed

    private void btn_registrarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarConActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_nuevoCon;
    public javax.swing.JButton btn_registrarCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txt_ConNombre;
    public javax.swing.JTextField txt_ConNumero;
    // End of variables declaration//GEN-END:variables
}
